# apiVersion: apps/v1
# kind: Deployment
# metadata: 
#   name: bookapi-deployment
#   namespace: default
#   labels:
#     app: bookapi
# spec: 
#   replicas: 2
#   selector:
#     matchLabels:
#       app: bookapi
#   template:
#     metadata:
#       labels:
#         app: bookapi
#     spec:
#       containers:
#       - name: book-api
#         image: book-api_go
#         imagePullPolicy: Never
#         ports:
#         - containerPort: 9010

# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: bookapi-nodeport
#   namespace: default
# spec:
#   type: NodePort
#   selector:
#     app: bookapi
#   ports:
#   - port: 8081
#     targetPort: 9010
#     nodePort: 30000

apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookapi
spec:
  selector:
    matchLabels:
      app: bookapi
  template:
    metadata:
      labels:
        app: bookapi
    spec:
      containers:
      - name: bookapi
        image: book-api_go
        imagePullPolicy: Never
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 9010
