version: "3.8"

services:
  go:
    build:
      context: .
    container_name: go
    ports:
      - 9010:9010
    depends_on:
      - "db"

  db:
    image: mysql:8.0.31
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: dbname
    volumes:
      - my-db:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  my-db:
